### ISSUE TITLE
Запушить образ приложения в Docker

### ISSUE THREAD

**Issue by artur-barsegyan** [tarantool/try-tarantool#30]
Имя контейнера должно выглядеть так: **tarantool/getting-started**

Ожидается, что можно будет подключиться по HTTP и бинарному порту роутера через следующую команду:
`docker run -p 3301:3301 -p 8081:8081 tarantool/getting-started`

Обратить особое внимание на работу вкладки Tutorial в запущенном контейнере.

**Comment by vasiliy-t** [comment]
Образ собираем на opensource версии Tarantool, добавляем в образе рок space-explorer
